### Login (obtener token)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "student",
  "password": "student123"
}

### Listar todos los blueprints (scope blueprints.read)
GET http://localhost:8080/api/v1/blueprints
Authorization: Bearer {{access_token}}

### Blueprints por autor (scope blueprints.read)
GET http://localhost:8080/api/v1/blueprints/john
Authorization: Bearer {{access_token}}

### Blueprint por autor y nombre (scope blueprints.read)
GET http://localhost:8080/api/v1/blueprints/john/house
Authorization: Bearer {{access_token}}

### Crear blueprint (scope blueprints.write)
POST http://localhost:8080/api/v1/blueprints
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "author": "samuel",
  "name": "office",
  "points": [{"x": 1, "y": 1}, {"x": 2, "y": 2}]
}

### Agregar punto a un blueprint (scope blueprints.write)
PUT http://localhost:8080/api/v1/blueprints/samuel/office/points
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "x": 5,
  "y": 7
}
